### ISSUE TITLE
Install doesn't include header files

### ISSUE THREAD

**Issue by MSumulong** [cjh1/protobuf#5]
I'm using this project to compile protobuf under Windows using the MinGW toolchain. It works great except the include folder isn't copied over.

**Comment by cjh1** [comment]
@MSumulong Feel free to submit a PR

**Comment by MSumulong** [comment]
I just looked at the current PRs and looks like @alex85k did it: https://github.com/cjh1/protobuf/pull/4

**Comment by cjh1** [comment]
@MSumulong you right, if you can confirm it works for you I will merge it.

**Comment by MSumulong** [comment]
Worked for me.

**Comment by cjh1** [comment]
Fixed by #4
